# Generated by Django 2.1.2 on 2018-10-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools_Image',
            new_name='ToolsImage',
        ),
    ]
